/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kebunsampahapp;
import dao.KomoditiDAO;
import dao.LaporanPanenDAO;
import entities.LaporanPanen;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Amanda Widya
 */
public class Kebun_LaporanPanen extends javax.swing.JFrame {
  private KomoditiDAO komoditiDAO;
    /**
     * Creates new form LaporanPanen
     */
    public Kebun_LaporanPanen() {
        komoditiDAO = new KomoditiDAO();
        initComponents();
         populateDropdownKomoditi();
         populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelLaporanPanen = new javax.swing.JTable();
        HapusButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TambahPesananButton1 = new javax.swing.JButton();
        DaftarPelangganButton1 = new javax.swing.JButton();
        DaftarKomoditiButton1 = new javax.swing.JButton();
        LaporanPanenButton1 = new javax.swing.JButton();
        LaporanPenjualanButton1 = new javax.swing.JButton();
        MainMenuButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dropdownKomoditi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tfBeratPesanan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateTanggal = new com.toedter.calendar.JDateChooser();
        ClearButton = new javax.swing.JButton();
        TambahPanenButton = new javax.swing.JButton();

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Daftar Pelanggan");

        jLabel4.setText("Nama Komoditi");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Nama", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.green);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        TabelLaporanPanen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Komoditi", "Berat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelLaporanPanen);

        HapusButton.setBackground(new java.awt.Color(255, 0, 51));
        HapusButton.setForeground(new java.awt.Color(255, 255, 255));
        HapusButton.setText("Hapus");
        HapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusButtonActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setText("Bumi Hijau");

        TambahPesananButton1.setBackground(new java.awt.Color(204, 255, 0));
        TambahPesananButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/shopping-cart.png"))); // NOI18N
        TambahPesananButton1.setText("Tambah Pesanan");
        TambahPesananButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TambahPesananButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahPesananButton1ActionPerformed(evt);
            }
        });

        DaftarPelangganButton1.setBackground(new java.awt.Color(204, 255, 0));
        DaftarPelangganButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/man.png"))); // NOI18N
        DaftarPelangganButton1.setText("Daftar Pelanggan");
        DaftarPelangganButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DaftarPelangganButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarPelangganButton1ActionPerformed(evt);
            }
        });

        DaftarKomoditiButton1.setBackground(new java.awt.Color(204, 255, 0));
        DaftarKomoditiButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/wheat.png"))); // NOI18N
        DaftarKomoditiButton1.setText("Daftar Komoditi");
        DaftarKomoditiButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DaftarKomoditiButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarKomoditiButton1ActionPerformed(evt);
            }
        });

        LaporanPanenButton1.setBackground(new java.awt.Color(204, 255, 0));
        LaporanPanenButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/report.png"))); // NOI18N
        LaporanPanenButton1.setText("Laporan Panen");
        LaporanPanenButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        LaporanPanenButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPanenButton1ActionPerformed(evt);
            }
        });

        LaporanPenjualanButton1.setBackground(new java.awt.Color(204, 255, 0));
        LaporanPenjualanButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/seo-report.png"))); // NOI18N
        LaporanPenjualanButton1.setText("Laporan Penjualan");
        LaporanPenjualanButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        LaporanPenjualanButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPenjualanButton1ActionPerformed(evt);
            }
        });

        MainMenuButton1.setBackground(new java.awt.Color(204, 255, 0));
        MainMenuButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/back.png"))); // NOI18N
        MainMenuButton1.setText("Main Menu");
        MainMenuButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        MainMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DaftarPelangganButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DaftarKomoditiButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LaporanPanenButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LaporanPenjualanButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(41, 41, 41))
            .addComponent(MainMenuButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TambahPesananButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(DaftarPelangganButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DaftarKomoditiButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LaporanPanenButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LaporanPenjualanButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(MainMenuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(TambahPesananButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(489, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LaporanPanen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 36))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel3.setText("Nama Hasil Panen");

        dropdownKomoditi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownKomoditiActionPerformed(evt);
            }
        });

        jLabel6.setText("Berat Panen ");

        tfBeratPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBeratPesananActionPerformed(evt);
            }
        });

        jLabel5.setText("Tanggal Panen");

        ClearButton.setBackground(new java.awt.Color(255, 51, 51));
        ClearButton.setForeground(new java.awt.Color(255, 255, 255));
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        TambahPanenButton.setBackground(new java.awt.Color(18, 129, 0));
        TambahPanenButton.setForeground(new java.awt.Color(255, 255, 255));
        TambahPanenButton.setText("Tambah Panen");
        TambahPanenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahPanenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropdownKomoditi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBeratPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TambahPanenButton))
                    .addComponent(jDateTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropdownKomoditi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBeratPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton)
                    .addComponent(TambahPanenButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(HapusButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(HapusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TambahPanenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahPanenButtonActionPerformed
      // Get values from the UI components
    String komoditiNama = (String) dropdownKomoditi.getSelectedItem();
    String beratPesananStr = tfBeratPesanan.getText();
    Date tanggal = jDateTanggal.getDate();

    // Validate the values
    if (komoditiNama == null || beratPesananStr.isEmpty() || tanggal == null) {
        JOptionPane.showMessageDialog(this, "Please fill in all the fields.");
        return;
    }

    double beratPesanan;
    try {
        beratPesanan = Double.parseDouble(beratPesananStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid number for berat.");
        return;
    }

    // Create a LaporanPanen object
    LaporanPanen laporanPanen = new LaporanPanen(0, new java.sql.Date(tanggal.getTime()), komoditiNama, beratPesanan);

    // Insert the object into the database
    LaporanPanenDAO laporanPanenDAO = new LaporanPanenDAO();
    boolean isSuccess = laporanPanenDAO.addLaporanPanen(laporanPanen);

    // Show a success or failure message to the user
    if (isSuccess) {
        JOptionPane.showMessageDialog(this, "Laporan panen berhasil ditambahkan.");
        // Optionally, you can clear the input fields or refresh the table if needed
        tfBeratPesanan.setText("");
        jDateTanggal.setDate(null);
        dropdownKomoditi.setSelectedIndex(0);
    } else {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menambahkan laporan panen.");
    }
    populateTable();
    }//GEN-LAST:event_TambahPanenButtonActionPerformed

    private void tfBeratPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBeratPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBeratPesananActionPerformed

    private void HapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusButtonActionPerformed
   // Get the selected row index
    int selectedRowIndex = TabelLaporanPanen.getSelectedRow();

    // Check if a row is selected
    if (selectedRowIndex >= 0) {
        // Get the values of the selected row
        String tanggal = TabelLaporanPanen.getValueAt(selectedRowIndex, 0).toString(); // Assuming date is in the first column
        String komoditi = TabelLaporanPanen.getValueAt(selectedRowIndex, 1).toString(); // Assuming commodity name is in the second column
        double berat = Double.parseDouble(TabelLaporanPanen.getValueAt(selectedRowIndex, 2).toString()); // Assuming weight is in the third column

        // Remove the row from the table
        DefaultTableModel tableModel = (DefaultTableModel) TabelLaporanPanen.getModel();
        tableModel.removeRow(selectedRowIndex);

        // Remove the row from the database using the date, commodity name, and weight
        LaporanPanenDAO laporanPanenDAO = new LaporanPanenDAO();
        boolean deleted = laporanPanenDAO.deleteLaporanPanenByDetails(tanggal, komoditi, berat);
        if (deleted) {
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus dari database.");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data dari database.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus.");
    }
    }//GEN-LAST:event_HapusButtonActionPerformed

    private void dropdownKomoditiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownKomoditiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownKomoditiActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
    dropdownKomoditi.setSelectedIndex(0); // Set the selected index of dropdownKomoditi to the default (first item)
    tfBeratPesanan.setText(""); // Clear the text field tfBeratPanen
    jDateTanggal.setDate(null); // Set the date in jDateTanggal to null (clear the date)
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void TambahPesananButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahPesananButton1ActionPerformed
        Kebun_TambahPesanan KebunTambahPesanan = new Kebun_TambahPesanan();

        // Set the new window to be visible
        KebunTambahPesanan.setVisible(true);

        // Dispose of the current window (CurrentWindow.java)
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_TambahPesananButton1ActionPerformed

    private void DaftarPelangganButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarPelangganButton1ActionPerformed
        Kebun_DaftarPelanggan Kebun_DaftarPelanggan = new Kebun_DaftarPelanggan();

        // Set the new window to be visible
        Kebun_DaftarPelanggan.setVisible(true);

        // Dispose of the current window (CurrentWindow.java)
        this.dispose();
    }//GEN-LAST:event_DaftarPelangganButton1ActionPerformed

    private void DaftarKomoditiButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarKomoditiButton1ActionPerformed
        Kebun_DaftarKomoditi Kebun_DaftarKomoditi = new Kebun_DaftarKomoditi();

        // Set the new window to be visible
        Kebun_DaftarKomoditi.setVisible(true);

        // Dispose of the current window (CurrentWindow.java)
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_DaftarKomoditiButton1ActionPerformed

    private void LaporanPenjualanButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPenjualanButton1ActionPerformed
        Kebun_Laporan Kebun_Laporan = new Kebun_Laporan();

        // Set the new window to be visible
        Kebun_Laporan.setVisible(true);

        // Dispose of the current window (CurrentWindow.java)
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_LaporanPenjualanButton1ActionPerformed

    private void MainMenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuButton1ActionPerformed
        MainWindow MainWindow = new MainWindow();

        // Set the new window to be visible
        MainWindow.setVisible(true);

        // Dispose of the current window (CurrentWindow.java)
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_MainMenuButton1ActionPerformed

    private void LaporanPanenButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPanenButton1ActionPerformed
         Kebun_LaporanPanen Kebun_LaporanPanen = new Kebun_LaporanPanen();

        // Set the new window to be visible
        Kebun_LaporanPanen.setVisible(true);

        // Dispose of the current window (CurrentWindow.java)
        this.dispose();         // TODO add your handling code here:   // TODO add your handling code here:
    }//GEN-LAST:event_LaporanPanenButton1ActionPerformed
    private void populateDropdownKomoditi() {
        List<String> komoditiNamaList = komoditiDAO.getAllKomoditiNama();

        for (String komoditiNama : komoditiNamaList) {
            dropdownKomoditi.addItem(komoditiNama);
        }
    }
    
     private void populateTable() {
        DefaultTableModel tableModel = (DefaultTableModel) TabelLaporanPanen.getModel();
        tableModel.setRowCount(0); // Clear existing rows

        LaporanPanenDAO laporanPanenDAO = new LaporanPanenDAO();
        // Fetch data from the database
        List<LaporanPanen> laporanPanenList = laporanPanenDAO.getAllLaporanPanen();

        // Populate the table with fetched data
        for (LaporanPanen laporanPanen : laporanPanenList) {
            Object[] rowData = {
                laporanPanen.getPanenTanggal(),
                laporanPanen.getPanenKomoditi(),
                laporanPanen.getPanenBerat()
            };
            tableModel.addRow(rowData);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kebun_LaporanPanen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kebun_LaporanPanen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kebun_LaporanPanen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kebun_LaporanPanen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kebun_LaporanPanen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DaftarKomoditiButton1;
    private javax.swing.JButton DaftarPelangganButton1;
    private javax.swing.JButton HapusButton;
    private javax.swing.JButton LaporanPanenButton1;
    private javax.swing.JButton LaporanPenjualanButton1;
    private javax.swing.JButton MainMenuButton1;
    private javax.swing.JTable TabelLaporanPanen;
    private javax.swing.JButton TambahPanenButton;
    private javax.swing.JButton TambahPesananButton1;
    private javax.swing.JComboBox<String> dropdownKomoditi;
    private com.toedter.calendar.JDateChooser jDateTanggal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField tfBeratPesanan;
    // End of variables declaration//GEN-END:variables
}
