/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kebunsampahapp;

import dao.PelangganDAO;
import entities.Pelanggan;
import dao.PesananDAO;
import entities.Pesanan;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;





/**
 *
 * @author ibadj
 */
public class Kebun_TambahPesanan extends javax.swing.JFrame {
private PelangganDAO pelangganDAO;
private PesananDAO pesananDAO;

    /**
     * Creates new form KebunTambahPesanan
     */
    public Kebun_TambahPesanan() {
        initComponents();
pelangganDAO = new PelangganDAO();
populateDropdownPelanggan();
Connection dbConnection = DatabaseConnection.getConnection();
PesananDAO pesananDAO = new PesananDAO(dbConnection);
populateTable();

  
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        javax.swing.JButton DeleteButton = new javax.swing.JButton();
        javax.swing.JButton SelesaiButton = new javax.swing.JButton();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JButton SortButton = new javax.swing.JButton();
        SortClearButton = new javax.swing.JButton();
        FromDateChooser = new com.toedter.calendar.JDateChooser();
        ToDateChooser = new com.toedter.calendar.JDateChooser();
        comboBoxStatus = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TambahPesananButton1 = new javax.swing.JButton();
        DaftarPelangganButton1 = new javax.swing.JButton();
        DaftarKomoditiButton1 = new javax.swing.JButton();
        LaporanPanenButton1 = new javax.swing.JButton();
        LaporanPenjualanButton1 = new javax.swing.JButton();
        MainMenuButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelPesanan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        dropdownPelanggan = new javax.swing.JComboBox<>();
        tfAlamat = new javax.swing.JTextField();
        tfNoTelp = new javax.swing.JTextField();
        tfTanggal = new com.toedter.calendar.JDateChooser();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JButton TambahItemButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(777, 518));

        DeleteButton.setBackground(new java.awt.Color(255, 0, 51));
        DeleteButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        SelesaiButton.setBackground(new java.awt.Color(51, 153, 255));
        SelesaiButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        SelesaiButton.setForeground(new java.awt.Color(255, 255, 255));
        SelesaiButton.setText("Selesai");
        SelesaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelesaiButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setText("From");

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setText("To");

        SortButton.setBackground(new java.awt.Color(51, 102, 0));
        SortButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        SortButton.setForeground(new java.awt.Color(255, 255, 255));
        SortButton.setText("Sort");
        SortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortButtonActionPerformed(evt);
            }
        });

        SortClearButton.setBackground(new java.awt.Color(51, 51, 255));
        SortClearButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        SortClearButton.setForeground(new java.awt.Color(255, 255, 255));
        SortClearButton.setText("Refresh");
        SortClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortClearButtonActionPerformed(evt);
            }
        });

        comboBoxStatus.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        comboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "all", "belum lunas", "lunas", " " }));
        comboBoxStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxStatusItemStateChanged(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setText("Bumi Hijau");

        TambahPesananButton1.setBackground(new java.awt.Color(204, 255, 0));
        TambahPesananButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/shopping-cart.png"))); // NOI18N
        TambahPesananButton1.setText("Tambah Pesanan");
        TambahPesananButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TambahPesananButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahPesananButton1ActionPerformed(evt);
            }
        });

        DaftarPelangganButton1.setBackground(new java.awt.Color(204, 255, 0));
        DaftarPelangganButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/man.png"))); // NOI18N
        DaftarPelangganButton1.setText("Daftar Pelanggan");
        DaftarPelangganButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DaftarPelangganButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarPelangganButton1ActionPerformed(evt);
            }
        });

        DaftarKomoditiButton1.setBackground(new java.awt.Color(204, 255, 0));
        DaftarKomoditiButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/wheat.png"))); // NOI18N
        DaftarKomoditiButton1.setText("Daftar Komoditi");
        DaftarKomoditiButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DaftarKomoditiButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarKomoditiButton1ActionPerformed(evt);
            }
        });

        LaporanPanenButton1.setBackground(new java.awt.Color(204, 255, 0));
        LaporanPanenButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/report.png"))); // NOI18N
        LaporanPanenButton1.setText("Laporan Panen");
        LaporanPanenButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        LaporanPanenButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPanenButton1ActionPerformed(evt);
            }
        });

        LaporanPenjualanButton1.setBackground(new java.awt.Color(204, 255, 0));
        LaporanPenjualanButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/seo-report.png"))); // NOI18N
        LaporanPenjualanButton1.setText("Laporan Penjualan");
        LaporanPenjualanButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        LaporanPenjualanButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPenjualanButton1ActionPerformed(evt);
            }
        });

        MainMenuButton1.setBackground(new java.awt.Color(204, 255, 0));
        MainMenuButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/back.png"))); // NOI18N
        MainMenuButton1.setText("Main Menu");
        MainMenuButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        MainMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DaftarPelangganButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DaftarKomoditiButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LaporanPanenButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LaporanPenjualanButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(41, 41, 41))
            .addComponent(MainMenuButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TambahPesananButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(DaftarPelangganButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DaftarKomoditiButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LaporanPanenButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LaporanPenjualanButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(MainMenuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(TambahPesananButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(489, Short.MAX_VALUE)))
        );

        TabelPesanan.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TabelPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Tanggal", "Macam Komoditi", "Total Harga", "status", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelPesanan);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tambah Pesanan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 36))); // NOI18N
        jPanel3.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Nama Pelanggan");

        dropdownPelanggan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dropdownPelangganItemStateChanged(evt);
            }
        });

        tfAlamat.setEditable(false);

        tfNoTelp.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("Tanggal");

        TambahItemButton.setBackground(new java.awt.Color(51, 51, 255));
        TambahItemButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TambahItemButton.setForeground(new java.awt.Color(255, 255, 255));
        TambahItemButton.setText("+ Tambah Pesanan");
        TambahItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(dropdownPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TambahItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdownPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TambahItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelesaiButton)
                        .addGap(129, 129, 129)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(FromDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ToDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SortButton)
                                .addGap(18, 18, 18)
                                .addComponent(SortClearButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SelesaiButton)
                            .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FromDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SortButton)
                                .addComponent(SortClearButton)))
                        .addGap(15, 15, 15)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void SortClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortClearButtonActionPerformed
populateTable();
    }//GEN-LAST:event_SortClearButtonActionPerformed

    private void SortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortButtonActionPerformed
    // Get the selected from and to dates
    Date fromDate = FromDateChooser.getDate();
    Date toDate = ToDateChooser.getDate();

    if (fromDate == null || toDate == null) {
        JOptionPane.showMessageDialog(this, "Please select both from and to dates.");
        return;
    }

    // Construct the SQL query to fetch sorted orders within the date range
    String query = "SELECT * FROM pesanan WHERE Pesanan_tanggal BETWEEN ? AND ? ORDER BY Pesanan_tanggal";

    try (Connection connection = DatabaseConnection.getConnection();
         PreparedStatement statement = connection.prepareStatement(query)) {

        statement.setDate(1, new java.sql.Date(fromDate.getTime()));
        statement.setDate(2, new java.sql.Date(toDate.getTime()));

        ResultSet resultSet = statement.executeQuery();

        // Create a temporary list to store sorted orders
        List<Object[]> sortedOrders = new ArrayList<>();

        // Populate the temporary list with sorted orders
        while (resultSet.next()) {
            String id = resultSet.getString("Pesanan_id");
            String nama = resultSet.getString("Pesanan_nama");
            String tanggal = resultSet.getString("Pesanan_tanggal");
            String macamKomoditi = resultSet.getString("Pesanan_macamkomoditi");
            double totalHarga = resultSet.getDouble("Pesanan_totalharga");
            String status = resultSet.getString("Pesanan_status");

            // Add the order details to the temporary list
            sortedOrders.add(new Object[]{id, nama, tanggal, macamKomoditi, totalHarga, status});
        }

        // Clear existing data from the table
        DefaultTableModel model = (DefaultTableModel) TabelPesanan.getModel();
        model.setRowCount(0);

        // Populate the table with sorted orders
        for (Object[] order : sortedOrders) {
            model.addRow(order);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Failed to sort orders: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_SortButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
     // Step 1: Get the selected row index from the table
    int selectedRowIndex = TabelPesanan.getSelectedRow();
    if (selectedRowIndex == -1) {
        // No row is selected, display an error message or handle the situation
        JOptionPane.showMessageDialog(this, "Please select an order to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Step 2: Get the order ID (or any unique identifier) from the selected row
    String orderID = TabelPesanan.getValueAt(selectedRowIndex, TabelPesanan.getColumn("ID").getModelIndex()).toString();
    // Here, "ID" is the name of the column representing the order ID in your table

    // Step 3: Delete the corresponding entry from the database
    PesananDAO pesananDAO = new PesananDAO(DatabaseConnection.getConnection());
    try {
        boolean deleteSuccess = pesananDAO.deletePesananByID(orderID);
        if (deleteSuccess) {
            // Deletion successful, update the table or display a success message
            System.out.println("Order deleted successfully!");
            populateTable();
        } else {
            // Deletion failed, display an error message or handle the situation
            JOptionPane.showMessageDialog(this, "Failed to delete order!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        // Deletion failed due to a foreign key constraint
        JOptionPane.showMessageDialog(this, "Cannot delete order with ID " + orderID + " because it has related order details. Please delete the order details first.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void dropdownPelangganItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dropdownPelangganItemStateChanged
    if (evt.getStateChange() == ItemEvent.SELECTED) {
        Pelanggan selectedPelanggan = (Pelanggan) dropdownPelanggan.getSelectedItem();
        if (selectedPelanggan != null) {
            tfAlamat.setText(selectedPelanggan.getAlamat()); // Assuming getAlamat() returns the address
            tfNoTelp.setText(selectedPelanggan.getNoTelp()); // Assuming getNoTelp() returns the phone number
        }
    }
    }//GEN-LAST:event_dropdownPelangganItemStateChanged

    private void TambahItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahItemButtonActionPerformed

    // Step 1: Retrieve Selected Pelanggan Information
    Pelanggan selectedPelanggan = (Pelanggan) dropdownPelanggan.getSelectedItem();
    String namaPelanggan = selectedPelanggan.getNama();
    String alamatPelanggan = selectedPelanggan.getAlamat();
    String noTelpPelanggan = selectedPelanggan.getNoTelp();

    // Step 2: Generate Order ID
    String orderID = generateOrderID();

    // Step 3: Retrieve Order Date
    
    Date orderDate = tfTanggal.getDate(); // Assuming tfTanggal is the date picker field

    // Step 4: Create Pesanan Object
    Pesanan pesanan = new Pesanan(orderID, namaPelanggan, orderDate, null, 0.0); // Assuming macamKomoditi and totalHarga are not set here

    // Step 5: Add Pesanan to Database
    PesananDAO pesananDAO = new PesananDAO(DatabaseConnection.getConnection());
    try {
        pesananDAO.addPesanan(pesanan);
        System.out.println("Pesanan added successfully!");
        // You can add a success message or perform any other action here
    } catch (SQLException e) {
        System.err.println("Error adding Pesanan: " + e.getMessage());
        // Handle the exception (display an error message, log the error, etc.)
    }
    populateTable();
}

// Method to generate order ID
private String generateOrderID() {
    String monthYear = new SimpleDateFormat("MM-yyyy").format(tfTanggal.getDate()); // Assuming tfTanggal is the date picker field
    String query = "SELECT COUNT(*) AS count FROM pesanan WHERE Pesanan_id LIKE ?";
    try (Connection connection = DatabaseConnection.getConnection();
         PreparedStatement statement = connection.prepareStatement(query)) {

        statement.setString(1, "%" + monthYear + "%");
        ResultSet resultSet = statement.executeQuery();
        if (resultSet.next()) {
            int count = resultSet.getInt("count");
            return (count + 1) + "/Kebun/" + monthYear;
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return null; // Handle error or return a default value
    }//GEN-LAST:event_TambahItemButtonActionPerformed

    private void SelesaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelesaiButtonActionPerformed
     // Get the selected row index from TabelPesanan
    int selectedRowIndex = TabelPesanan.getSelectedRow();
    
    if (selectedRowIndex != -1) {  // Check if a row is selected
        // Get the order ID from the selected row
        String orderId = TabelPesanan.getValueAt(selectedRowIndex, 0).toString();  // Assuming order ID is in the first column (index 0)

        // Update the status in the database
        PesananDAO pesananDAO = new PesananDAO(DatabaseConnection.getConnection());
        boolean updated = pesananDAO.updateStatusToLunas(orderId);

        if (updated) {
            // Update the table to reflect the change
            DefaultTableModel model = (DefaultTableModel) TabelPesanan.getModel();
            model.setValueAt("lunas", selectedRowIndex, model.getColumnCount() - 1);  // Assuming status is in the last column

            // Show a success message or perform any other action
            JOptionPane.showMessageDialog(this, "Status updated to 'lunas' for order ID: " + orderId);
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update status for order ID: " + orderId);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row in the table.");
    }
    }//GEN-LAST:event_SelesaiButtonActionPerformed

    private void comboBoxStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxStatusItemStateChanged
         if (evt.getStateChange() == ItemEvent.SELECTED) {
        String selectedStatus = comboBoxStatus.getSelectedItem().toString();
        filterTableByStatus(selectedStatus);
    }
    }//GEN-LAST:event_comboBoxStatusItemStateChanged

    private void TambahPesananButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahPesananButton1ActionPerformed
        Kebun_TambahPesanan KebunTambahPesanan = new Kebun_TambahPesanan();

        // Set the new window to be visible
        KebunTambahPesanan.setVisible(true);

        // Dispose of the current window (CurrentWindow.java)
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_TambahPesananButton1ActionPerformed

    private void DaftarPelangganButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarPelangganButton1ActionPerformed
        Kebun_DaftarPelanggan Kebun_DaftarPelanggan = new Kebun_DaftarPelanggan();

        // Set the new window to be visible
        Kebun_DaftarPelanggan.setVisible(true);

        // Dispose of the current window (CurrentWindow.java)
        this.dispose();
    }//GEN-LAST:event_DaftarPelangganButton1ActionPerformed

    private void DaftarKomoditiButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarKomoditiButton1ActionPerformed
        Kebun_DaftarKomoditi Kebun_DaftarKomoditi = new Kebun_DaftarKomoditi();

        // Set the new window to be visible
        Kebun_DaftarKomoditi.setVisible(true);

        // Dispose of the current window (CurrentWindow.java)
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_DaftarKomoditiButton1ActionPerformed

    private void LaporanPanenButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPanenButton1ActionPerformed
        Kebun_LaporanPanen Kebun_LaporanPanen = new Kebun_LaporanPanen();

        // Set the new window to be visible
        Kebun_LaporanPanen.setVisible(true);

        // Dispose of the current window (CurrentWindow.java)
        this.dispose();         // TODO add your handling code here:   // TODO add your handling code here:
    }//GEN-LAST:event_LaporanPanenButton1ActionPerformed

    private void LaporanPenjualanButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPenjualanButton1ActionPerformed
        Kebun_Laporan Kebun_Laporan = new Kebun_Laporan();

        // Set the new window to be visible
        Kebun_Laporan.setVisible(true);

        // Dispose of the current window (CurrentWindow.java)
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_LaporanPenjualanButton1ActionPerformed

    private void MainMenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuButton1ActionPerformed
        MainWindow MainWindow = new MainWindow();

        // Set the new window to be visible
        MainWindow.setVisible(true);

        // Dispose of the current window (CurrentWindow.java)
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_MainMenuButton1ActionPerformed
private void populateDropdownPelanggan() {
    List<Pelanggan> pelangganList = pelangganDAO.getAllPelanggan();
    
    // Sort the list alphabetically based on the name of the Pelanggan
    Collections.sort(pelangganList, new Comparator<Pelanggan>() {
        @Override
        public int compare(Pelanggan p1, Pelanggan p2) {
            return p1.getNama().compareTo(p2.getNama());
        }
    });

    DefaultComboBoxModel<Pelanggan> model = new DefaultComboBoxModel<>();
    for (Pelanggan pelanggan : pelangganList) {
        model.addElement(pelanggan);
    }
    dropdownPelanggan.setModel(model);
}


private String generateID(String formattedDate) {
    // Count existing entries with the same month-year
    int count = 0;
    DefaultTableModel model = (DefaultTableModel) TabelPesanan.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        String existingID = (String) model.getValueAt(i, 0); // Assuming ID is in the first column
        if (existingID.endsWith(formattedDate)) {
            count++;
        }
    }

    // Generate the ID with nn/Kebun/month-year format
    return String.format("%02d/Kebun/%s", count + 1, formattedDate);
}

private void populateTable() {
    DefaultTableModel model = (DefaultTableModel) TabelPesanan.getModel();
    model.setRowCount(0); // Clear existing data
    
    try (Connection connection = DatabaseConnection.getConnection();
         PreparedStatement statement = connection.prepareStatement("SELECT * FROM pesanan ORDER BY Pesanan_status ASC");
         ResultSet resultSet = statement.executeQuery()) {
        
        while (resultSet.next()) {
            String id = resultSet.getString("Pesanan_id");
            String nama = resultSet.getString("Pesanan_nama");
            String tanggal = resultSet.getString("Pesanan_tanggal");
            String macamKomoditi = resultSet.getString("Pesanan_macamkomoditi");
            double totalHarga = resultSet.getDouble("Pesanan_totalharga");
            String status = resultSet.getString("Pesanan_status");
            
            model.addRow(new Object[]{id, nama, tanggal, macamKomoditi, totalHarga, status});
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Failed to populate table: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    TabelPesanan.getColumn("Action").setCellRenderer(new TabelPesananRenderer());
    TabelPesanan.getColumn("Action").setCellEditor(new TabelPesananEditor(TabelPesanan));
}


private void filterTableByStatus(String selectedStatus) {
    DefaultTableModel model = (DefaultTableModel) TabelPesanan.getModel();
    TableRowSorter<TableModel> sorter = new TableRowSorter<>(model);
    TabelPesanan.setRowSorter(sorter);

    if (!selectedStatus.equalsIgnoreCase("all")) {
        RowFilter<Object, Object> rowFilter = new RowFilter<Object, Object>() {
            @Override
            public boolean include(Entry<? extends Object, ? extends Object> entry) {
                // Get the status from the entry (assuming it's in the second to last column)
                String status = entry.getStringValue(model.getColumnCount() - 2);
                return selectedStatus.equalsIgnoreCase(status);
            }
        };

        sorter.setRowFilter(rowFilter);
    } else {
        sorter.setRowFilter(null); // Remove the row filter to show all rows
    }
}


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kebun_DaftarKomoditi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kebun_DaftarKomoditi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kebun_DaftarKomoditi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kebun_DaftarKomoditi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kebun_TambahPesanan().setVisible(true);
            }
        });
    }

 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DaftarKomoditiButton1;
    private javax.swing.JButton DaftarPelangganButton1;
    private com.toedter.calendar.JDateChooser FromDateChooser;
    private javax.swing.JButton LaporanPanenButton1;
    private javax.swing.JButton LaporanPenjualanButton1;
    private javax.swing.JButton MainMenuButton1;
    private javax.swing.JButton SortClearButton;
    private javax.swing.JTable TabelPesanan;
    private javax.swing.JButton TambahPesananButton1;
    private com.toedter.calendar.JDateChooser ToDateChooser;
    private javax.swing.JComboBox<String> comboBoxStatus;
    private javax.swing.JComboBox<Pelanggan> dropdownPelanggan;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfNoTelp;
    private com.toedter.calendar.JDateChooser tfTanggal;
    // End of variables declaration//GEN-END:variables
}
