/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kebunsampahapp;


import dao.PelangganDAO;
import entities.Pelanggan;

import java.sql.SQLException;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ibadj
 */
public class Kebun_DaftarPelanggan extends javax.swing.JFrame {
    private PelangganDAO pelangganDAO;


    /**
     * Creates new form Kebun_DaftarPelanggan
     */
    public Kebun_DaftarPelanggan() {
        initComponents();
        pelangganDAO = new PelangganDAO();


        // Populate the table initially
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        javax.swing.JButton DeleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPelanggan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TambahPesananButton = new javax.swing.JButton();
        DaftarPelangganButton = new javax.swing.JButton();
        DaftarKomoditiButton = new javax.swing.JButton();
        LaporanPanenButton = new javax.swing.JButton();
        LaporanPenjualanButton = new javax.swing.JButton();
        MainMenuButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfNoTelp = new javax.swing.JTextField();
        javax.swing.JButton ClearButton = new javax.swing.JButton();
        javax.swing.JButton TambahPelangganButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        DeleteButton.setBackground(new java.awt.Color(204, 0, 0));
        DeleteButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        TabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Alamat", "No Telp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelPelanggan);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("Bumi Hijau");

        TambahPesananButton.setBackground(new java.awt.Color(204, 255, 0));
        TambahPesananButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/shopping-cart.png"))); // NOI18N
        TambahPesananButton.setText("Tambah Pesanan");
        TambahPesananButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TambahPesananButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahPesananButtonActionPerformed(evt);
            }
        });

        DaftarPelangganButton.setBackground(new java.awt.Color(204, 255, 0));
        DaftarPelangganButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/man.png"))); // NOI18N
        DaftarPelangganButton.setText("Daftar Pelanggan");
        DaftarPelangganButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DaftarPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarPelangganButtonActionPerformed(evt);
            }
        });

        DaftarKomoditiButton.setBackground(new java.awt.Color(204, 255, 0));
        DaftarKomoditiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/wheat.png"))); // NOI18N
        DaftarKomoditiButton.setText("Daftar Komoditi");
        DaftarKomoditiButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DaftarKomoditiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarKomoditiButtonActionPerformed(evt);
            }
        });

        LaporanPanenButton.setBackground(new java.awt.Color(204, 255, 0));
        LaporanPanenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/report.png"))); // NOI18N
        LaporanPanenButton.setText("Laporan Panen");
        LaporanPanenButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        LaporanPenjualanButton.setBackground(new java.awt.Color(204, 255, 0));
        LaporanPenjualanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/seo-report.png"))); // NOI18N
        LaporanPenjualanButton.setText("Laporan Penjualan");
        LaporanPenjualanButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        LaporanPenjualanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPenjualanButtonActionPerformed(evt);
            }
        });

        MainMenuButton.setBackground(new java.awt.Color(204, 255, 0));
        MainMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/back.png"))); // NOI18N
        MainMenuButton.setText("Main Menu");
        MainMenuButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        MainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DaftarPelangganButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DaftarKomoditiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LaporanPanenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LaporanPenjualanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(41, 41, 41))
            .addComponent(MainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TambahPesananButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(DaftarPelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DaftarKomoditiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LaporanPanenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LaporanPenjualanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(MainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(TambahPesananButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(489, Short.MAX_VALUE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tambah Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 24))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("Nomor Telepon");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("Alamat");

        ClearButton.setBackground(new java.awt.Color(255, 0, 51));
        ClearButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(255, 255, 255));
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        TambahPelangganButton.setBackground(new java.awt.Color(0, 153, 153));
        TambahPelangganButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TambahPelangganButton.setForeground(new java.awt.Color(255, 255, 255));
        TambahPelangganButton.setText("+ Tambah Pelanggan");
        TambahPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahPelangganButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(ClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TambahPelangganButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton)
                    .addComponent(TambahPelangganButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeleteButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened
    private void populateTable() {
     List<Pelanggan> pelangganList = pelangganDAO.getAllPelanggan();
    DefaultTableModel model = (DefaultTableModel) TabelPelanggan.getModel();

    // Debug: Print the number of pelanggan retrieved
    System.out.println("Number of pelanggan retrieved: " + pelangganList.size());

    // Sort the list alphabetically based on the name of the Pelanggan
    Collections.sort(pelangganList, new Comparator<Pelanggan>() {
        @Override
        public int compare(Pelanggan p1, Pelanggan p2) {
            return p1.getNama().compareTo(p2.getNama());
        }
    });

    // Clear existing data
    model.setRowCount(0);

    // Debug: Print the column names
    for (int i = 0; i < model.getColumnCount(); i++) {
        System.out.println("Column name " + i + ": " + model.getColumnName(i));
    }

    // Add rows to the table
    for (Pelanggan pelanggan : pelangganList) {
        System.out.println("Adding pelanggan to table: " + pelanggan.getNama() + ", " + pelanggan.getAlamat() + ", " + pelanggan.getNoTelp());
        model.addRow(new Object[]{pelanggan.getNama(), pelanggan.getAlamat(), pelanggan.getNoTelp()});
    }

    // Debug: Print the number of rows in the table model
    System.out.println("Number of rows in table model: " + model.getRowCount());
    }

    private void TambahPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahPelangganButtonActionPerformed
   // Get data from text fields
    String nama = tfNama.getText();
    String alamat = tfAlamat.getText();
    String noTelp = tfNoTelp.getText();

    // Validate input (you can add more validation as needed)
    if (nama.isEmpty() || alamat.isEmpty() || noTelp.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create a new Pelanggan object with the retrieved data
    Pelanggan newPelanggan = new Pelanggan(nama, alamat, noTelp);

    // Insert data into the database using PelangganDAO
    PelangganDAO pelangganDAO = new PelangganDAO();
    boolean success = pelangganDAO.addPelanggan(newPelanggan);

    if (success) {
        // If insertion is successful, update the table and clear text fields
        populateTable(); // Update table
        tfNama.setText(""); // Clear text fields
        tfAlamat.setText("");
        tfNoTelp.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Failed to add new pelanggan.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_TambahPelangganButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
    // Get the selected row index
    int selectedRow = TabelPelanggan.getSelectedRow();
    
    // Ensure a row is selected
    if (selectedRow >= 0) {
        // Get the pelanggan details from the selected row
        String pelangganNama = (String) TabelPelanggan.getValueAt(selectedRow, 0); // Assuming name is in the first column
        String pelangganAlamat = (String) TabelPelanggan.getValueAt(selectedRow, 1); // Assuming address is in the second column
        String pelangganNoTelp = (String) TabelPelanggan.getValueAt(selectedRow, 2); // Assuming phone number is in the third column

        // Confirm the deletion
        int confirm = JOptionPane.showConfirmDialog(this, "Ingin menghapus data?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            // Delete the pelanggan from the database
            boolean success = pelangganDAO.deletePelangganByDetails(pelangganNama, pelangganAlamat, pelangganNoTelp);

            // If deletion is successful, remove the row from the table
            if (success) {
                DefaultTableModel model = (DefaultTableModel) TabelPelanggan.getModel();
                model.removeRow(selectedRow);
                JOptionPane.showMessageDialog(this, "Pelanggan berhasil dihapus.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete pelanggan.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row to delete.");
    }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
    tfNama.setText("");
    tfAlamat.setText("");  
    tfNoTelp.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void DaftarPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarPelangganButtonActionPerformed
     Kebun_DaftarPelanggan Kebun_DaftarPelanggan = new Kebun_DaftarPelanggan();

    // Set the new window to be visible
    Kebun_DaftarPelanggan.setVisible(true);

    // Dispose of the current window (CurrentWindow.java)
    this.dispose(); 
    }//GEN-LAST:event_DaftarPelangganButtonActionPerformed

    private void TambahPesananButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahPesananButtonActionPerformed
    Kebun_TambahPesanan KebunTambahPesanan = new Kebun_TambahPesanan();

    // Set the new window to be visible
    KebunTambahPesanan.setVisible(true);

    // Dispose of the current window (CurrentWindow.java)
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_TambahPesananButtonActionPerformed

    private void LaporanPenjualanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPenjualanButtonActionPerformed
   Kebun_Laporan Kebun_Laporan = new Kebun_Laporan();

    // Set the new window to be visible
    Kebun_Laporan.setVisible(true);

    // Dispose of the current window (CurrentWindow.java)
    this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_LaporanPenjualanButtonActionPerformed

    private void MainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuButtonActionPerformed
     MainWindow MainWindow = new MainWindow();

    // Set the new window to be visible
    MainWindow.setVisible(true);

    // Dispose of the current window (CurrentWindow.java)
    this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_MainMenuButtonActionPerformed

    private void DaftarKomoditiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarKomoditiButtonActionPerformed
   Kebun_DaftarKomoditi Kebun_DaftarKomoditi = new Kebun_DaftarKomoditi();

    // Set the new window to be visible
    Kebun_DaftarKomoditi.setVisible(true);

    // Dispose of the current window (CurrentWindow.java)
    this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_DaftarKomoditiButtonActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kebun_DaftarPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kebun_DaftarPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kebun_DaftarPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kebun_DaftarPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kebun_DaftarPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DaftarKomoditiButton;
    private javax.swing.JButton DaftarPelangganButton;
    private javax.swing.JButton LaporanPanenButton;
    private javax.swing.JButton LaporanPenjualanButton;
    private javax.swing.JButton MainMenuButton;
    private javax.swing.JTable TabelPelanggan;
    private javax.swing.JButton TambahPesananButton;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNoTelp;
    // End of variables declaration//GEN-END:variables
}
